Added mediaPlaybackRequiresUserGesture flag with state disabled.
duckduckgo/privacy-configuration pull request #1767
Opened 2024-01-25 12:39 UTC by anikiki

**Asana Task/Github Issue:**

## Description

#### Reference
- [Config Reviewer Documentation](https://app.asana.com/0/1200890834746050/1204443212791216/f)
- [Config Maintainer Documentation](https://app.asana.com/0/1200890834746050/1200573250322769/f)
- [Feature Implementer Documentation](https://app.asana.com/0/1200890834746050/1201498956177210/f)

2024-01-26 11:40 UTC, anikiki commented on overrides/android-override.json
> +            "state": "disabled",
This will be enabled in Production when we want to use it (after the ship review, app release).

2024-01-30 10:49 UTC, marcosholgado commented on features/mediaPlaybackRequiresUserGesture.json
> +{
Files are named using `-` as separators so this file should be `media-playback-requires-user-gesture.json`

2024-01-30 11:09 UTC, marcosholgado approved these changes
LGTM

2024-01-31 12:31 UTC, anikiki commented on overrides/android-override.json
> +                    "domain": "upperbodystretch.com"
Added 2 domains as we found 2 more website with the same issue. See https://app.asana.com/0/1206374308645191/1206445562784324/f and https://app.asana.com/0/1163321984198618/1205995907661137

2024-02-01 18:30 UTC, anikiki commented on overrides/android-override.json
> +                    "domain": "facialwebcapture.cloud.itau.com.br"
Added 3 domains. See https://app.asana.com/0/0/1206420802766788/f and https://app.asana.com/0/0/1206420802766788/1206495276207661/f.

2024-02-02 11:44 UTC, anikiki commented on overrides/android-override.json
> +                    "domain": "tinder.com"
Added one more domain. See https://app.asana.com/0/0/1206420805430540/1206500180540104/f and https://app.asana.com/0/0/1206420805430540/1206495276207664/f.

2024-02-02 19:00 UTC, anikiki commented on overrides/android-override.json
> +                    "domain": "facialwebcapture.cloud.itau.com.br"
Added 2 domains. See https://app.asana.com/0/0/1206420802766788/1206497348822710/f and https://app.asana.com/0/0/1206420802766788/1206500790260328/f.

2024-02-05 13:17 UTC, marcosholgado approved these changes
LGTM

2024-02-05 13:21 UTC, SlayterDev requested changes
@anikiki we generally require reasons for exceptions for public review (which are stripped out when shipped to the client). Could you open GitHub issues in this repo for the exceptions and add their links to the `reason` keys? If some domains can be grouped under the same reason you can use the same issue link for them. Thanks!

2024-02-05 17:10 UTC, anikiki commented
> @anikiki we generally require reasons for exceptions for public review (which are stripped out when shipped to the client). Could you open GitHub issues in this repo for the exceptions and add their links to the `reason` keys? If some domains can be grouped under the same reason you can use the same issue link for them. Thanks!

@SlayterDev I created issues and updated the config with the reasons associated with the issues.

2024-02-05 17:14 UTC, merged