Additional instructions in the new issue template.
duckduckgo/privacy-configuration pull request #507
Opened 2022-09-30 21:34 UTC by kdzwinel

**Asana Task:** https://app.asana.com/0/0/1203055064411207/f

**Description**

- include additional instructions in the new issue template
- make the preview of the template readable
- replace "..." with "…" 👀

2022-09-30 21:50 UTC, SlayterDev requested changes
Just one minor typo 😁

2022-09-30 21:50 UTC, SlayterDev commented on .github/ISSUE_TEMPLATE/document-breakage.md
> +<!-- Each exception shoudl be documented. Please create an issue using template below before creating a new exception. -->
Typo in should*

2023-03-02 19:03 UTC, SlayterDev commented
@kdzwinel could you have a look at the requested changes here?

2023-04-11 16:33 UTC, GuiltyDolphin commented on .github/ISSUE_TEMPLATE/document-breakage.md
> +    - `https://tracker.com` <!-- url of the request that needs to be unblocked --> (`js` <!--resource type(s)-->) - <!--additional description-->
same as https://github.com/duckduckgo/privacy-configuration/pull/507/files#r1163070715

2023-04-11 16:34 UTC, GuiltyDolphin commented on .github/ISSUE_TEMPLATE/document-breakage.md
> +- … <!-- other site that's broken due to blocking of the same tracker -->
comments on a different line would be good, otherwise we have a lot of trailing space

2023-04-11 16:35 UTC, GuiltyDolphin commented on .github/ISSUE_TEMPLATE/document-breakage.md
> +<!-- Title should contain eTLD+1 of the tracker (and not the site that's broken). -->
Depends on the breakage. Sometimes it's the site, sometimes it's the tracker.

2023-04-29 01:02 UTC, jonathanKingston commented
@kdzwinel can we close or resolve the issues?

Could we instead use an issue form: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

2023-06-01 16:31 UTC, SlayterDev commented
Superseded by https://github.com/duckduckgo/privacy-configuration/pull/982

2023-06-01 16:31 UTC, closed without merging